# Generated by Django 2.1.2 on 2019-05-24 00:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Polaris', '0050_tb_fact_dnsip_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='tb_fact_nameid_info',
            name='zone_type',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Polaris.tb_fact_dnszone_info'),
        ),
    ]
