# Generated by Django 2.1.2 on 2019-06-02 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Polaris', '0055_auto_20190531_0845'),
    ]

    operations = [
        migrations.AddField(
            model_name='tb_fact_adminip_info',
            name='city',
            field=models.CharField(default='0', max_length=256),
        ),
        migrations.AddField(
            model_name='tb_fact_adminip_info',
            name='country',
            field=models.CharField(default='0', max_length=256),
        ),
    ]
