# Generated by Django 2.1.2 on 2019-06-02 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Polaris', '0056_auto_20190602_0226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tb_fact_adminip_info',
            name='node_id',
            field=models.CharField(default='0', max_length=256),
        ),
    ]
