# Generated by Django 2.1.2 on 2019-06-19 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Polaris', '0059_auto_20190610_2352'),
    ]

    operations = [
        migrations.CreateModel(
            name='tb_fact_detectdeviceavailability_select_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_ip', models.CharField(max_length=256)),
                ('vip_address', models.CharField(max_length=256)),
                ('availability', models.CharField(choices=[('enable', 'enable'), ('disable', 'disable')], max_length=256)),
                ('admin_isp', models.CharField(default='0', max_length=256)),
                ('create_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='tb_fact_zonetype_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone_name', models.CharField(max_length=256)),
                ('zone_status', models.CharField(choices=[('enable', 'enable'), ('disable', 'disable')], max_length=256)),
                ('zone_describe', models.CharField(max_length=256)),
            ],
        ),
    ]
