# Generated by Django 2.1.2 on 2019-06-19 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Polaris', '0063_remove_tb_fact_dnszone_info_zone_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='tb_fact_dnszone_info',
            name='zone_name',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='Polaris.tb_fact_zonetype_info'),
            preserve_default=False,
        ),
    ]
