# Generated by Django 2.1.2 on 2019-06-19 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Polaris', '0065_remove_tb_fact_nameid_info_zone_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='tb_fact_nameid_info',
            name='zone_type',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='Polaris.tb_fact_zonetype_info'),
            preserve_default=False,
        ),
    ]
