# Generated by Django 2.1.2 on 2019-05-10 05:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Polaris', '0018_tb_fact_ipset_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='tb_dimension_nameid_view_info_test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameid_resolve_type', models.CharField(choices=[('cname', 'cname'), ('a', 'a'), ('aaaa', 'aaaa')], default='a', max_length=10)),
                ('nameid_max_ip', models.IntegerField(default=1)),
                ('nameid_preferred', models.CharField(choices=[('rr', 'rr'), ('ratio', 'ratio')], default='rr', max_length=10)),
                ('nameid_status', models.CharField(max_length=256)),
                ('nameid_ttl', models.IntegerField(default=120)),
                ('nameid_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Polaris.tb_fact_nameid_info')),
                ('nameid_view_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Polaris.tb_fact_temp_view_info')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='tb_dimension_nameid_view_info_test',
            unique_together={('nameid_id', 'nameid_view_id')},
        ),
    ]
