# Generated by Django 2.1.2 on 2019-05-08 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Polaris', '0008_delete_tb_fact_ori_view_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='tb_fact_ori_view_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_address', models.CharField(max_length=256)),
                ('end_address', models.CharField(max_length=256)),
                ('country', models.CharField(max_length=256)),
                ('province', models.CharField(max_length=256)),
                ('city', models.CharField(max_length=256)),
                ('unknow_a', models.CharField(default='0', max_length=30)),
                ('isp', models.CharField(max_length=256)),
                ('unknow_b', models.CharField(default='0', max_length=30)),
                ('unknow_c', models.CharField(default='0', max_length=30)),
                ('unknow_d', models.CharField(default='0', max_length=30)),
                ('unknow_e', models.CharField(default='0', max_length=30)),
                ('unknow_f', models.CharField(default='0', max_length=30)),
                ('unknow_g', models.CharField(default='0', max_length=30)),
                ('unknow_h', models.CharField(default='0', max_length=30)),
                ('unknow_i', models.CharField(default='0', max_length=30)),
                ('unknow_j', models.CharField(default='0', max_length=30)),
                ('unknow_k', models.CharField(default='0', max_length=30)),
                ('unknow_l', models.CharField(default='0', max_length=30)),
                ('unknow_m', models.CharField(default='0', max_length=30)),
            ],
        ),
    ]
