# Generated by Django 2.1.2 on 2019-05-14 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Polaris', '0027_auto_20190514_1021'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tb_fact_dnszone_info',
        ),
    ]
