# Generated by Django 2.1.2 on 2019-05-22 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Polaris', '0042_auto_20190516_0757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tb_fact_detectdeviceavailability_info',
            name='availability',
            field=models.CharField(choices=[('enable', 'enable'), ('disable', 'disable')], max_length=256),
        ),
    ]
