# Generated by Django 2.1.2 on 2019-05-31 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Polaris', '0053_remove_tb_fact_device_info_node_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='tb_fact_device_info',
            name='node_id',
            field=models.CharField(default='0', max_length=256),
        ),
    ]
