# Generated by Django 2.1.2 on 2019-06-19 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tb_dimension_device_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vip_address', models.CharField(max_length=256)),
                ('realip_address', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='tb_dimension_nameid_view_cname_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameid_cname_ratio', models.IntegerField(default=1)),
                ('nameid_cname_status', models.CharField(choices=[('enable', 'enable'), ('disable', 'disable')], max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='tb_dimension_nameid_view_device_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameid_device_ratio', models.IntegerField(default=1)),
                ('nameid_device_status', models.CharField(choices=[('enable', 'enable'), ('disable', 'disable')], max_length=256)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='tb_dimension_nameid_view_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameid_resolve_type', models.CharField(choices=[('cname', 'cname'), ('a', 'a'), ('aaaa', 'aaaa')], default='a', max_length=10)),
                ('nameid_max_ip', models.IntegerField(default=1)),
                ('nameid_preferred', models.CharField(choices=[('rr', 'rr'), ('ratio', 'ratio')], default='rr', max_length=10)),
                ('nameid_status', models.CharField(choices=[('enable', 'enable'), ('disable', 'disable')], default='enable', max_length=256)),
                ('nameid_ttl', models.IntegerField(default=120)),
            ],
        ),
        migrations.CreateModel(
            name='tb_fact_adminip_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_id', models.CharField(default='0', max_length=256)),
                ('admin_ip', models.CharField(max_length=150, unique=True)),
                ('country', models.CharField(default='0', max_length=256)),
                ('isp', models.CharField(max_length=256)),
                ('region', models.CharField(max_length=256)),
                ('province', models.CharField(max_length=256)),
                ('city', models.CharField(default='0', max_length=256)),
                ('availability_status', models.CharField(choices=[('enable', 'enable'), ('disable', 'disable')], default='disable', max_length=256)),
                ('qos_status', models.CharField(choices=[('enable', 'enable'), ('disable', 'disable')], default='disable', max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='tb_fact_cname_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameid_cname', models.CharField(max_length=250, unique=True)),
                ('nameid_owner', models.CharField(max_length=256)),
                ('nameid_supplier', models.CharField(max_length=256)),
                ('nameid_business', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='tb_fact_detectdeviceavailability_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_ip', models.CharField(max_length=256)),
                ('vip_address', models.CharField(max_length=256)),
                ('availability', models.CharField(choices=[('enable', 'enable'), ('disable', 'disable')], max_length=256)),
                ('admin_isp', models.CharField(default='0', max_length=256)),
                ('create_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='tb_fact_detectdeviceavailability_select_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_ip', models.CharField(max_length=256)),
                ('vip_address', models.CharField(max_length=256)),
                ('availability', models.CharField(choices=[('enable', 'enable'), ('disable', 'disable')], max_length=256)),
                ('admin_isp', models.CharField(default='0', max_length=256)),
                ('create_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='tb_fact_detectdeviceavailability_standard_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_isp', models.CharField(max_length=150, unique=True)),
                ('total_value', models.IntegerField()),
                ('absolute_value', models.IntegerField()),
                ('relative_rate', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='tb_fact_detecttask_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detect_name', models.CharField(max_length=150, unique=True)),
                ('detect_frency', models.IntegerField()),
                ('detect_frency_unit', models.CharField(choices=[('second', 'second'), ('minute', 'minute'), ('hour', 'hour'), ('day', 'day'), ('week', 'week'), ('month', 'month')], default='second', max_length=256)),
                ('effective_time', models.IntegerField(default=15)),
                ('effective_time_unit', models.CharField(choices=[('second', 'second'), ('minute', 'minute'), ('hour', 'hour'), ('day', 'day'), ('week', 'week'), ('month', 'month')], default='second', max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='tb_fact_device_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_id', models.CharField(default='0', max_length=256)),
                ('vip_status', models.CharField(choices=[('enable', 'enable'), ('disable', 'disable')], max_length=256)),
                ('vip_address', models.CharField(max_length=150, unique=True)),
                ('vip_bandwidth', models.CharField(max_length=256)),
                ('vip_enable_switch', models.CharField(choices=[('enable', 'enable'), ('disable', 'disable')], default='enable', max_length=256)),
                ('node_country', models.CharField(default='0', max_length=256)),
                ('node_isp', models.CharField(default='0', max_length=256)),
                ('node_region', models.CharField(default='0', max_length=256)),
                ('node_province', models.CharField(default='0', max_length=256)),
                ('node_city', models.CharField(default='0', max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='tb_fact_dnsip_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dns_ip', models.CharField(max_length=150, unique=True)),
                ('dns_status', models.CharField(choices=[('enable', 'enable'), ('disable', 'disable')], max_length=256)),
                ('dns_describe', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='tb_fact_dnstype_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dns_name', models.CharField(max_length=254, unique=True)),
                ('dns_status', models.CharField(choices=[('enable', 'enable'), ('disable', 'disable')], max_length=256)),
                ('dns_describe', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='tb_fact_dnszone_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('internet_type', models.CharField(max_length=256)),
                ('record_type', models.CharField(max_length=256)),
                ('record_content', models.CharField(max_length=256)),
                ('record_name', models.CharField(max_length=256)),
                ('record_ttl', models.IntegerField(default=120)),
                ('dns_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Polaris.tb_fact_dnstype_info')),
            ],
        ),
        migrations.CreateModel(
            name='tb_fact_ipset_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_address', models.CharField(max_length=256)),
                ('end_address', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='tb_fact_nameid_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameid_name', models.CharField(max_length=254, unique=True)),
                ('nameid_status', models.CharField(choices=[('enable', 'enable'), ('disable', 'disable')], max_length=256)),
                ('dns_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Polaris.tb_fact_dnstype_info')),
            ],
        ),
        migrations.CreateModel(
            name='tb_fact_nameid_infos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameid_name', models.CharField(max_length=254, unique=True)),
                ('nameid_status', models.CharField(choices=[('enable', 'enable'), ('disable', 'disable')], max_length=256)),
                ('dns_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Polaris.tb_fact_dnstype_info')),
            ],
        ),
        migrations.CreateModel(
            name='tb_fact_nameidpolicy_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policy_name', models.CharField(max_length=254, unique=True)),
                ('policy_status', models.CharField(choices=[('enable', 'enable'), ('disable', 'disable')], max_length=256)),
                ('policy_describe', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='tb_fact_ori_view_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_address', models.CharField(max_length=256)),
                ('end_address', models.CharField(max_length=256)),
                ('country', models.CharField(max_length=256)),
                ('region', models.CharField(default='0', max_length=256)),
                ('province', models.CharField(max_length=256)),
                ('city', models.CharField(max_length=256)),
                ('unknow_a', models.CharField(default='0', max_length=30)),
                ('isp', models.CharField(max_length=256)),
                ('unknow_b', models.CharField(default='0', max_length=30)),
                ('unknow_c', models.CharField(default='0', max_length=30)),
                ('unknow_d', models.CharField(default='0', max_length=30)),
                ('unknow_e', models.CharField(default='0', max_length=30)),
                ('unknow_f', models.CharField(default='0', max_length=30)),
                ('unknow_g', models.CharField(default='0', max_length=30)),
                ('unknow_h', models.CharField(default='0', max_length=30)),
                ('unknow_i', models.CharField(default='0', max_length=30)),
                ('unknow_j', models.CharField(default='0', max_length=30)),
                ('unknow_k', models.CharField(default='0', max_length=30)),
                ('unknow_l', models.CharField(default='0', max_length=30)),
                ('unknow_m', models.CharField(default='0', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='tb_fact_realdevice_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_status', models.CharField(max_length=256)),
                ('ip_address', models.CharField(max_length=256)),
                ('ip_bandwidth', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='tb_fact_temp_view_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('view_father_id', models.IntegerField(default=0)),
                ('view_default', models.CharField(default='*', max_length=256)),
                ('view_country', models.CharField(default='*', max_length=256)),
                ('view_isp', models.CharField(default='*', max_length=256)),
                ('view_region', models.CharField(default='*', max_length=256)),
                ('view_province', models.CharField(default='*', max_length=256)),
                ('view_city', models.CharField(default='*', max_length=256)),
                ('view_grade_name', models.CharField(default='*', max_length=256)),
                ('view_grade', models.IntegerField(default=0)),
                ('view_father_grade', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='tb_fact_viewtype_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('view_type', models.CharField(max_length=256)),
                ('view_describe', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='tb_fact_zonetype_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone_name', models.CharField(max_length=256)),
                ('zone_status', models.CharField(choices=[('enable', 'enable'), ('disable', 'disable')], max_length=256)),
                ('zone_describe', models.CharField(max_length=256)),
            ],
        ),
        migrations.AddField(
            model_name='tb_fact_temp_view_info',
            name='view_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Polaris.tb_fact_viewtype_info'),
        ),
        migrations.AddField(
            model_name='tb_fact_nameid_infos',
            name='nameid_policy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Polaris.tb_fact_nameidpolicy_info'),
        ),
        migrations.AddField(
            model_name='tb_fact_nameid_infos',
            name='zone_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Polaris.tb_fact_zonetype_info'),
        ),
        migrations.AddField(
            model_name='tb_fact_nameid_info',
            name='nameid_policy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Polaris.tb_fact_nameidpolicy_info'),
        ),
        migrations.AddField(
            model_name='tb_fact_nameid_info',
            name='zone_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Polaris.tb_fact_zonetype_info'),
        ),
        migrations.AddField(
            model_name='tb_fact_ipset_info',
            name='view_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Polaris.tb_fact_temp_view_info'),
        ),
        migrations.AddField(
            model_name='tb_fact_dnszone_info',
            name='zone_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Polaris.tb_fact_zonetype_info'),
        ),
        migrations.AddField(
            model_name='tb_fact_dnsip_info',
            name='dns_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Polaris.tb_fact_dnstype_info'),
        ),
        migrations.AddField(
            model_name='tb_dimension_nameid_view_info',
            name='nameid_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Polaris.tb_fact_nameid_info'),
        ),
        migrations.AddField(
            model_name='tb_dimension_nameid_view_info',
            name='nameid_view_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Polaris.tb_fact_temp_view_info'),
        ),
        migrations.AddField(
            model_name='tb_dimension_nameid_view_device_info',
            name='nameid_device_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Polaris.tb_fact_device_info'),
        ),
        migrations.AddField(
            model_name='tb_dimension_nameid_view_device_info',
            name='nameid_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Polaris.tb_fact_nameid_info'),
        ),
        migrations.AddField(
            model_name='tb_dimension_nameid_view_device_info',
            name='nameid_view_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Polaris.tb_fact_temp_view_info'),
        ),
        migrations.AddField(
            model_name='tb_dimension_nameid_view_cname_info',
            name='nameid_cname_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Polaris.tb_fact_cname_info'),
        ),
        migrations.AddField(
            model_name='tb_dimension_nameid_view_cname_info',
            name='nameid_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Polaris.tb_fact_nameid_info'),
        ),
        migrations.AddField(
            model_name='tb_dimension_nameid_view_cname_info',
            name='nameid_view_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Polaris.tb_fact_temp_view_info'),
        ),
        migrations.AddField(
            model_name='tb_dimension_device_info',
            name='vip_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Polaris.tb_fact_device_info'),
        ),
        migrations.AlterUniqueTogether(
            name='tb_dimension_nameid_view_info',
            unique_together={('nameid_id', 'nameid_view_id')},
        ),
        migrations.AlterUniqueTogether(
            name='tb_dimension_nameid_view_device_info',
            unique_together={('nameid_id', 'nameid_view_id', 'nameid_device_id')},
        ),
        migrations.AlterUniqueTogether(
            name='tb_dimension_nameid_view_cname_info',
            unique_together={('nameid_id', 'nameid_view_id', 'nameid_cname_id')},
        ),
    ]
