# Generated by Django 2.1.2 on 2019-06-19 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Polaris', '0002_auto_20190619_1141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tb_fact_nameid_info',
            name='nameid_status',
            field=models.CharField(choices=[('disable', 'disable')], max_length=256),
        ),
        migrations.AlterField(
            model_name='tb_fact_zonetype_info',
            name='zone_name',
            field=models.CharField(max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='tb_fact_zonetype_info',
            name='zone_status',
            field=models.CharField(choices=[('disable', 'disable')], max_length=256),
        ),
    ]
