# Generated by Django 2.1.2 on 2019-06-27 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Polaris', '0003_auto_20190619_1253'),
    ]

    operations = [
        migrations.CreateModel(
            name='tb_fact_user_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(max_length=256)),
                ('password', models.CharField(max_length=256)),
                ('uuid', models.IntegerField(default=120)),
                ('captcha', models.IntegerField(default=120)),
            ],
        ),
    ]
