# Generated by Django 2.1.2 on 2019-06-27 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Polaris', '0004_tb_fact_user_info'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tb_fact_user_info',
            old_name='userName',
            new_name='username',
        ),
        migrations.RemoveField(
            model_name='tb_fact_user_info',
            name='uuid',
        ),
    ]
