# Generated by Django 2.1.2 on 2019-05-08 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Polaris', '0006_tb_fact_ori_view_info_tb_fact_temp_view_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='tb_fact_ori_view_info',
            name='unknow_b',
            field=models.CharField(default='0', max_length=30),
        ),
        migrations.AddField(
            model_name='tb_fact_ori_view_info',
            name='unknow_c',
            field=models.CharField(default='0', max_length=30),
        ),
        migrations.AddField(
            model_name='tb_fact_ori_view_info',
            name='unknow_d',
            field=models.CharField(default='0', max_length=30),
        ),
        migrations.AddField(
            model_name='tb_fact_ori_view_info',
            name='unknow_e',
            field=models.CharField(default='0', max_length=30),
        ),
        migrations.AddField(
            model_name='tb_fact_ori_view_info',
            name='unknow_f',
            field=models.CharField(default='0', max_length=30),
        ),
        migrations.AddField(
            model_name='tb_fact_ori_view_info',
            name='unknow_g',
            field=models.CharField(default='0', max_length=30),
        ),
        migrations.AddField(
            model_name='tb_fact_ori_view_info',
            name='unknow_h',
            field=models.CharField(default='0', max_length=30),
        ),
        migrations.AddField(
            model_name='tb_fact_ori_view_info',
            name='unknow_i',
            field=models.CharField(default='0', max_length=30),
        ),
        migrations.AddField(
            model_name='tb_fact_ori_view_info',
            name='unknow_j',
            field=models.CharField(default='0', max_length=30),
        ),
        migrations.AddField(
            model_name='tb_fact_ori_view_info',
            name='unknow_k',
            field=models.CharField(default='0', max_length=30),
        ),
        migrations.AddField(
            model_name='tb_fact_ori_view_info',
            name='unknow_l',
            field=models.CharField(default='0', max_length=30),
        ),
        migrations.AddField(
            model_name='tb_fact_ori_view_info',
            name='unknow_m',
            field=models.CharField(default='0', max_length=30),
        ),
        migrations.AlterField(
            model_name='tb_fact_ori_view_info',
            name='unknow_a',
            field=models.CharField(default='0', max_length=30),
        ),
    ]
