# Generated by Django 2.1.2 on 2019-05-14 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Polaris', '0029_tb_fact_dnszone_info'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tb_fact_dnszone_info',
            name='dns_type',
        ),
        migrations.DeleteModel(
            name='tb_fact_dnszone_info',
        ),
    ]
