# Generated by Django 2.1.2 on 2019-05-15 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Polaris', '0032_auto_20190514_1130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tb_fact_adminip_info',
            name='status',
            field=models.CharField(choices=[('enable', 'enable'), ('disable', 'disable')], default='disable', max_length=256),
        ),
    ]
