# Generated by Django 2.1.2 on 2019-06-27 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Polaris', '0005_auto_20190627_0806'),
    ]

    operations = [
        migrations.AddField(
            model_name='tb_fact_user_info',
            name='uuid',
            field=models.CharField(default='', max_length=256),
            preserve_default=False,
        ),
    ]
