# Generated by Django 2.1.2 on 2019-07-12 05:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Polaris', '0007_auto_20190703_0154'),
    ]

    operations = [
        migrations.CreateModel(
            name='tb_dimension_backend_nameid_view_cname_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameid_cname_ratio', models.IntegerField(default=1)),
                ('nameid_cname_status', models.CharField(choices=[('enable', 'enable'), ('disable', 'disable')], max_length=256)),
                ('nameid_cname_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Polaris.tb_fact_cname_info')),
            ],
        ),
        migrations.CreateModel(
            name='tb_dimension_backend_nameid_view_device_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameid_device_ratio', models.IntegerField(default=1)),
                ('nameid_device_status', models.CharField(choices=[('enable', 'enable'), ('disable', 'disable')], max_length=256)),
                ('nameid_device_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Polaris.tb_fact_device_info')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AlterField(
            model_name='tb_fact_nameid_info',
            name='nameid_status',
            field=models.CharField(choices=[('enable', 'enable'), ('disable', 'disable')], max_length=256),
        ),
        migrations.AddField(
            model_name='tb_dimension_backend_nameid_view_device_info',
            name='nameid_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Polaris.tb_fact_nameid_info'),
        ),
        migrations.AddField(
            model_name='tb_dimension_backend_nameid_view_device_info',
            name='nameid_view_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Polaris.tb_fact_temp_view_info'),
        ),
        migrations.AddField(
            model_name='tb_dimension_backend_nameid_view_cname_info',
            name='nameid_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Polaris.tb_fact_nameid_info'),
        ),
        migrations.AddField(
            model_name='tb_dimension_backend_nameid_view_cname_info',
            name='nameid_view_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Polaris.tb_fact_temp_view_info'),
        ),
        migrations.AlterUniqueTogether(
            name='tb_dimension_backend_nameid_view_device_info',
            unique_together={('nameid_id', 'nameid_view_id', 'nameid_device_id')},
        ),
        migrations.AlterUniqueTogether(
            name='tb_dimension_backend_nameid_view_cname_info',
            unique_together={('nameid_id', 'nameid_view_id', 'nameid_cname_id')},
        ),
    ]
