# Generated by Django 2.1.2 on 2019-05-08 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Polaris', '0007_auto_20190508_1316'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tb_fact_ori_view_info',
        ),
    ]
