# Generated by Django 2.1.2 on 2019-05-30 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Polaris', '0051_tb_fact_nameid_info_zone_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='tb_fact_device_info',
            name='node_city',
            field=models.CharField(default='0', max_length=256),
        ),
        migrations.AddField(
            model_name='tb_fact_device_info',
            name='node_country',
            field=models.CharField(default='0', max_length=256),
        ),
        migrations.AddField(
            model_name='tb_fact_device_info',
            name='node_province',
            field=models.CharField(default='0', max_length=256),
        ),
        migrations.AddField(
            model_name='tb_fact_device_info',
            name='node_region',
            field=models.CharField(default='0', max_length=256),
        ),
    ]
