# Generated by Django 2.1.2 on 2019-06-10 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Polaris', '0058_auto_20190610_2351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tb_fact_detectdeviceavailability_standard_info',
            name='node_isp',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
