# Generated by Django 2.1.2 on 2019-06-19 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Polaris', '0064_tb_fact_dnszone_info_zone_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tb_fact_nameid_info',
            name='zone_type',
        ),
    ]
