# Generated by Django 2.1.2 on 2019-04-23 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glbs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tb_fact_dnstype_info',
            name='dns_name',
            field=models.CharField(max_length=254, unique=True),
        ),
    ]
