# Generated by Django 2.1.2 on 2019-04-23 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glbs', '0003_auto_20190423_1240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tb_fact_nameid_info',
            name='nameid_name',
            field=models.CharField(max_length=254, unique=True),
        ),
    ]
