# Generated by Django 2.1.2 on 2019-04-24 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glbs', '0004_auto_20190423_1310'),
    ]

    operations = [
        migrations.AddField(
            model_name='tb_fact_device_info',
            name='vip_enable_switch',
            field=models.CharField(default='enable', max_length=256),
        ),
    ]
