# Generated by Django 2.1.2 on 2019-04-24 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glbs', '0005_tb_fact_device_info_vip_enable_switch'),
    ]

    operations = [
        migrations.CreateModel(
            name='tb_fact_cname_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameid_cname', models.CharField(max_length=256)),
                ('nameid_owner', models.CharField(max_length=256)),
            ],
        ),
    ]
