# Generated by Django 2.1.2 on 2019-04-24 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('glbs', '0006_tb_fact_cname_info'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tb_dimension_nameid_view_cname_info',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='tb_dimension_nameid_view_cname_info',
            name='nameid_id',
        ),
        migrations.RemoveField(
            model_name='tb_dimension_nameid_view_cname_info',
            name='nameid_view_id',
        ),
        migrations.DeleteModel(
            name='tb_dimension_nameid_view_cname_info',
        ),
    ]
