# Generated by Django 2.1.2 on 2019-04-26 02:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('glbs', '0008_auto_20190424_0716'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tb_dimension_nameid_view_cname_info',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='tb_dimension_nameid_view_cname_info',
            name='nameid_cname_id',
        ),
        migrations.RemoveField(
            model_name='tb_dimension_nameid_view_cname_info',
            name='nameid_id',
        ),
        migrations.RemoveField(
            model_name='tb_dimension_nameid_view_cname_info',
            name='nameid_view_id',
        ),
        migrations.AlterModelOptions(
            name='tb_dimension_nameid_view_device_info',
            options={'ordering': ['id']},
        ),
        migrations.DeleteModel(
            name='tb_dimension_nameid_view_cname_info',
        ),
        migrations.DeleteModel(
            name='tb_fact_cname_info',
        ),
    ]
