# Generated by Django 2.1.2 on 2019-04-26 02:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('glbs', '0009_auto_20190426_0221'),
    ]

    operations = [
        migrations.CreateModel(
            name='tb_dimension_nameid_view_cname_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameid_cname_ratio', models.IntegerField(default=1)),
                ('nameid_cname_status', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='tb_fact_cname_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameid_cname', models.CharField(max_length=256)),
                ('nameid_owner', models.CharField(max_length=256)),
                ('nameid_supplier', models.CharField(max_length=256)),
                ('nameid_business', models.CharField(max_length=256)),
            ],
        ),
        migrations.AddField(
            model_name='tb_dimension_nameid_view_cname_info',
            name='nameid_cname_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='glbs.tb_fact_cname_info'),
        ),
        migrations.AddField(
            model_name='tb_dimension_nameid_view_cname_info',
            name='nameid_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='glbs.tb_fact_nameid_info'),
        ),
        migrations.AddField(
            model_name='tb_dimension_nameid_view_cname_info',
            name='nameid_view_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='glbs.tb_fact_view_info'),
        ),
        migrations.AlterUniqueTogether(
            name='tb_dimension_nameid_view_cname_info',
            unique_together={('nameid_id', 'nameid_view_id', 'nameid_cname_id')},
        ),
    ]
