# Generated by Django 2.1.2 on 2019-04-26 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glbs', '0010_auto_20190426_0222'),
    ]

    operations = [
        migrations.AddField(
            model_name='tb_fact_device_info',
            name='node_isp',
            field=models.CharField(default='0', max_length=256),
        ),
    ]
