# Generated by Django 2.1.2 on 2019-04-27 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glbs', '0011_tb_fact_device_info_node_isp'),
    ]

    operations = [
        migrations.CreateModel(
            name='tb_fact_adminip_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_id', models.IntegerField()),
                ('admin_ip', models.CharField(max_length=256)),
                ('isp', models.CharField(max_length=256)),
                ('region', models.CharField(max_length=256)),
                ('province', models.CharField(max_length=256)),
                ('status', models.CharField(default='disable', max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='tb_fact_detecttask_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detect_name', models.CharField(max_length=256)),
                ('detect_frency', models.IntegerField()),
            ],
        ),
    ]
