# Generated by Django 2.1.2 on 2019-04-28 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glbs', '0013_tb_fact_detectdeviceavailability_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='tb_fact_detectdeviceavailability_info',
            name='create_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
