# Generated by Django 2.1.2 on 2019-05-14 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Polaris', '0024_auto_20190513_0213'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tb_fact_dnszone_info',
            old_name='ns_address',
            new_name='internet_type',
        ),
        migrations.RenameField(
            model_name='tb_fact_dnszone_info',
            old_name='ns_name',
            new_name='record_content',
        ),
        migrations.RenameField(
            model_name='tb_fact_dnszone_info',
            old_name='zone_soa',
            new_name='record_name',
        ),
        migrations.RenameField(
            model_name='tb_fact_dnszone_info',
            old_name='ns_ttl',
            new_name='record_ttl',
        ),
        migrations.AlterField(
            model_name='tb_fact_dnszone_info',
            name='dns_type',
            field=models.CharField(max_length=256),
        ),
    ]
