# Generated by Django 2.1.2 on 2019-05-07 05:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Polaris', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tb_dimension_nameid_view_device_info',
            name='nameid_device_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Polaris.tb_fact_device_info'),
        ),
    ]
