# Generated by Django 2.1.2 on 2019-05-07 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Polaris', '0002_auto_20190507_0558'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tb_temp_device_info',
        ),
    ]
