# Generated by Django 2.1.2 on 2019-05-07 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Polaris', '0003_delete_tb_temp_device_info'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tb_dimension_nameid_view_device_info',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='tb_dimension_nameid_view_device_info',
            name='nameid_device_id',
        ),
    ]
