# Generated by Django 2.1.2 on 2019-05-09 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Polaris', '0009_tb_fact_ori_view_info'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tb_fact_temp_view_info',
            name='view_type',
        ),
        migrations.DeleteModel(
            name='tb_fact_temp_view_info',
        ),
    ]
