# Generated by Django 2.1.2 on 2019-05-09 08:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Polaris', '0012_auto_20190509_0821'),
    ]

    operations = [
        migrations.CreateModel(
            name='tb_fact_temp_view_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('view_father_id', models.IntegerField(default=0)),
                ('view_default', models.CharField(max_length=256)),
                ('view_country', models.CharField(max_length=256)),
                ('view_isp', models.CharField(max_length=256)),
                ('view_region', models.CharField(max_length=256)),
                ('view_province', models.CharField(max_length=256)),
                ('view_city', models.CharField(max_length=256)),
                ('view_grade_name', models.CharField(max_length=256)),
                ('view_grade', models.IntegerField(default=0)),
                ('view_father_grade', models.IntegerField(default=0)),
                ('view_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Polaris.tb_fact_viewtype_info')),
            ],
        ),
    ]
