# Generated by Django 2.1.2 on 2019-05-09 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Polaris', '0016_tb_fact_temp_view_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='tb_fact_ori_view_info',
            name='region',
            field=models.CharField(default='0', max_length=256),
        ),
    ]
