# Generated by Django 2.1.2 on 2019-05-10 04:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Polaris', '0017_tb_fact_ori_view_info_region'),
    ]

    operations = [
        migrations.CreateModel(
            name='tb_fact_ipset_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_address', models.CharField(max_length=256)),
                ('end_address', models.CharField(max_length=256)),
                ('view_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Polaris.tb_fact_temp_view_info')),
            ],
        ),
    ]
