# Generated by Django 2.1.2 on 2019-05-10 06:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Polaris', '0019_auto_20190510_0527'),
    ]

    operations = [
        migrations.CreateModel(
            name='tb_dimension_nameid_view_device_info_test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameid_device_ratio', models.IntegerField(default=1)),
                ('nameid_device_status', models.CharField(max_length=256)),
                ('nameid_device_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Polaris.tb_fact_device_info')),
                ('nameid_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Polaris.tb_fact_nameid_info')),
                ('nameid_view_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Polaris.tb_fact_temp_view_info')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='tb_dimension_nameid_view_device_info_test',
            unique_together={('nameid_id', 'nameid_view_id', 'nameid_device_id')},
        ),
    ]
