# Generated by Django 2.1.2 on 2019-05-14 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Polaris', '0025_auto_20190514_1010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tb_fact_dnszone_info',
            name='dns_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Polaris.tb_fact_dnstype_info'),
        ),
    ]
