# Generated by Django 2.1.2 on 2019-05-15 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Polaris', '0037_auto_20190515_1329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tb_fact_nameid_info',
            name='nameid_status',
            field=models.CharField(choices=[('enable', 'enable'), ('disable', 'disable')], max_length=256),
        ),
    ]
