# Generated by Django 2.1.2 on 2019-05-15 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Polaris', '0039_auto_20190515_1333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tb_fact_nameidpolicy_info',
            name='policy_status',
            field=models.CharField(choices=[('enable', 'enable'), ('disable', 'disable')], max_length=256),
        ),
    ]
