# Generated by Django 2.1.2 on 2019-05-16 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Polaris', '0040_auto_20190515_1334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tb_fact_cname_info',
            name='nameid_cname',
            field=models.CharField(max_length=250, unique=True),
        ),
    ]
