# Generated by Django 2.1.2 on 2019-05-16 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Polaris', '0041_auto_20190516_0302'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tb_fact_adminip_info',
            old_name='status',
            new_name='availability_status',
        ),
        migrations.AddField(
            model_name='tb_fact_adminip_info',
            name='qos_status',
            field=models.CharField(choices=[('enable', 'enable'), ('disable', 'disable')], default='disable', max_length=256),
        ),
    ]
