# Generated by Django 2.1.2 on 2019-05-22 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Polaris', '0043_auto_20190522_0511'),
    ]

    operations = [
        migrations.AddField(
            model_name='tb_fact_detecttask_info',
            name='detect_frency_unit',
            field=models.CharField(choices=[('second', 'second'), ('minute', 'minute'), ('hour', 'hour'), ('day', 'day'), ('week', 'week'), ('month', 'month')], default='second', max_length=256),
        ),
        migrations.AddField(
            model_name='tb_fact_detecttask_info',
            name='effective_time',
            field=models.IntegerField(default=15),
        ),
        migrations.AddField(
            model_name='tb_fact_detecttask_info',
            name='effective_time_unit',
            field=models.CharField(choices=[('second', 'second'), ('minute', 'minute'), ('hour', 'hour'), ('day', 'day'), ('week', 'week'), ('month', 'month')], default='second', max_length=256),
        ),
    ]
