# Generated by Django 2.1.2 on 2019-05-22 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Polaris', '0047_auto_20190522_0610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tb_fact_device_info',
            name='vip_address',
            field=models.CharField(max_length=250, unique=True),
        ),
    ]
