# Generated by Django 2.1.2 on 2019-05-22 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Polaris', '0049_auto_20190522_0620'),
    ]

    operations = [
        migrations.CreateModel(
            name='tb_fact_dnsip_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dns_ip', models.CharField(max_length=150, unique=True)),
                ('dns_status', models.CharField(choices=[('enable', 'enable'), ('disable', 'disable')], max_length=256)),
                ('dns_describe', models.CharField(max_length=256)),
                ('dns_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Polaris.tb_fact_dnstype_info')),
            ],
        ),
    ]
