# Generated by Django 2.1.2 on 2019-05-31 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Polaris', '0052_auto_20190530_1036'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tb_fact_device_info',
            name='node_id',
        ),
    ]
