# Generated by Django 2.1.2 on 2019-06-19 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Polaris', '0060_tb_fact_detectdeviceavailability_select_info_tb_fact_zonetype_info'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tb_fact_dnszone_info',
            name='zone_name',
        ),
    ]
