# Generated by Django 2.1.2 on 2019-06-19 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Polaris', '0066_tb_fact_nameid_info_zone_type'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='tb_fact_nameid_info',
            new_name='tb_fact_nameid_infos',
        ),
    ]
